// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package assets

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed logo.png
var ResourceLogoPngData []byte
var ResourceLogoPng = &fyne.StaticResource{
	StaticName:    "logo.png",
	StaticContent: ResourceLogoPngData,
}

//go:embed flight.svg
var ResourceFlightSvgData []byte
var ResourceFlightSvg = &fyne.StaticResource{
	StaticName:    "flight.svg",
	StaticContent: ResourceFlightSvgData,
}

//go:embed AVLedger-wordmark-dark-720.png
var ResourceWordmarkDarkPngData []byte
var ResourceWordmarkDarkPng = &fyne.StaticResource{
	StaticName:    "AVLedger-wordmark-dark-720.png",
	StaticContent: ResourceWordmarkDarkPngData,
}

//go:embed AVLedger-wordmark-light-720.png
var ResourceWordmarkLightPngData []byte
var ResourceWordmarkLightPng = &fyne.StaticResource{
	StaticName:    "AVLedger-wordmark-light-720.png",
	StaticContent: ResourceWordmarkLightPngData,
}
